startUrl: "https://en.wikipedia.org/wiki/Main_Page"
timeoutMs: 10000
concurrency: 8
maxDepth: 5
backoffBaseMs: 100
backoffMaxMs: 10000
backoffJitterMs: 500
backoffRetries: 3
robotsTimeoutMs: 5000
redis:
  host: "redis"
  port: 6379

